#!/usr/bin/env bun
import { spawnSync } from "bun";
import { writeFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";

async function runGit(args: string[]) {
    const proc = spawnSync(["git", ...args]);
    if (proc.exitCode !== 0) {
        throw new Error(`Git command failed: git ${args.join(" ")}\n${proc.stderr.toString()}`);
    }
    return proc.stdout.toString().trim();
}

async function main() {
    const summary = process.argv[2];
    const details = process.argv[3] || summary;

    if (!summary) {
        console.error("❌ 错误: 请提供会话小结作为第一个参数。");
        process.exit(1);
    }

    const sessionsDir = join(process.cwd(), "sessions");
    if (!existsSync(sessionsDir)) {
        mkdirSync(sessionsDir, { recursive: true });
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const filename = `session_${timestamp}.md`;
    const filePath = join(sessionsDir, filename);

    const fullContent = `# AI Session Summary - ${new Date().toLocaleString()}

## 🚀 会话小结
${summary}

## 📝 详细记录
${details}

---
*Generated by Bun CodeView Session Sync*
`;

    console.log(`📄 正在创建会话文件: ${filename}`);
    writeFileSync(filePath, fullContent);

    try {
        console.log("📦 执行 git add .");
        await runGit(["add", "."]);

        console.log(`💾 执行 git commit -m "Session: ${summary}"`);
        await runGit(["commit", "-m", `Session: ${summary}`]);

        console.log("⬆️ 执行 git push");
        await runGit(["push"]);

        console.log("✅ 会话已同步并推送到远程仓库！");
    } catch (e) {
        console.error(`❌ 同步失败: ${e.message}`);
        process.exit(1);
    }
}

main().catch(console.error);
